version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "direct"
    open-pull-requests-limit: 10
    target-branch: main
    reviewers:
      - "titouanfreville"
    assignees:
      - "titouanfreville"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "direct"
    open-pull-requests-limit: 5
    target-branch: main
    reviewers:
      - "titouanfreville"
    assignees:
      - "titouanfreville"
